- name: "Create directories for rules {{ item }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
    - "{{ rule_storage_dir }}"
    - "{{ rule_tmp_dir }}"


- name: "Upload rule files"
  notify: "Restart Loki service"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ rule_storage_dir }}/{{ item | basename }}"
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - "{{ rule_source_dir }}/*.yml"
