---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  tasks:
    # https://github.com/ansible/molecule/issues/3587#issuecomment-1158650179
    - name: "Include default vars"
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions: [ 'yml' ]

    - name: "Sanity check the Loki daemon"
      retries: 5
      delay: 1
      register: this
      failed_when: "loki_version not in this.content"
      ansible.builtin.uri:
        url: "http://localhost:{{ loki_port }}/metrics"
        return_content: true

    - name: "Ensure that locgli is installed and able to run"
      ansible.builtin.command: 
        cmd: logcli --version
      register: cmd1
      failed_when: cmd1.rc != 0

    - name: "Check logcli version"
      ansible.builtin.assert:
        that: "'version {{ loki_version }}' in cmd1.stderr"
        success_msg: "logcli version {{ loki_version }} is installed and working"
        fail_msg: "logcli version {{ loki_version }} is not installed or not working correctly"
